name: 'Qualify'

on:
  push:
    branches-ignore:
      - 'release-*'

concurrency:
  group: 'qualify-${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

jobs:
  qualify:
    name: qualify
    runs-on: semversie-runner
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm ci
      - name: run tests
        run: npm test

  semVersie:
    name: semVersie
    runs-on: semversie-runner
    permissions:
      contents: read
    outputs:
      release: ${{ steps.semVersie.outputs.release }}
      release-notes: ${{ steps.semVersie.outputs.release-notes }}
      prerelease: ${{ steps.semVersie.outputs.prerelease }}
      tag: ${{ steps.semVersie.outputs.tag }}
      version: ${{ steps.semVersie.outputs.version }}
      version-pep-440: ${{ steps.semVersie.outputs['version-pep-440'] }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        timeout-minutes: 5
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm ci
      - name: build distribution
        run: npm run build
      - name: remove node_modules
        run: rm -rf node_modules
      - id: semVersie
        name: semVersie
        uses: ./
        with:
          release-notes-format: 'docs/resources/release-format.md'

  formatting:
    name: Check code formatting
    runs-on: semversie-runner
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'
      - name: check formatting
        run: npx prettier --check .

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
