name: 'Qualify'

on:
  push:
    branches-ignore:
      - 'release-*'

concurrency:
  group: 'qualify-${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

jobs:
  qualify:
    name: qualify
    runs-on: semversie-runner
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm install
      - name: run tests
        run: npm test

  semVersie:
    name: semVersie
    runs-on: semversie-runner
    permissions:
      contents: read
    outputs:
      release: ${{ steps.semVersie.outputs.release }}
      release-notes: ${{ steps.semVersie.outputs.release-notes }}
      prerelease: ${{ steps.semVersie.outputs.prerelease }}
      tag: ${{ steps.semVersie.outputs.tag }}
      version: ${{ steps.semVersie.outputs.version }}
      version-pep-440: ${{ steps.semVersie.outputs['version-pep-440'] }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        timeout-minutes: 5
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm install
      - name: build distribution
        run: npm run build
      - id: semVersie
        name: semVersie
        uses: ./
        with:
          release-notes-format: 'docs/resources/release-format.md'

  formatting:
    name: Check code formatting
    runs-on: semversie-runner
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm install
      - name: check formatting
        run: npm run format
      - name: verify no formatting changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Code is not properly formatted. Please run 'npm run format' and commit the changes.";
            exit 1;
          else
            echo "Code is properly formatted.";
          fi

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
